# Generated by Django 4.1.3 on 2023-02-26 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='updated_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
